Traceback (most recent call last):
  File "/home/lucy/miniconda3/envs/skan_doc/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/lucy/miniconda3/envs/skan_doc/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/lucy/miniconda3/envs/skan_doc/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/lucy/miniconda3/envs/skan_doc/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/lucy/miniconda3/envs/skan_doc/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/lucy/miniconda3/envs/skan_doc/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/lucy/miniconda3/envs/skan_doc/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/lucy/miniconda3/envs/skan_doc/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from skan import _testdata
g0, c0 = skeleton_to_csgraph(_testdata.skeleton0)
g1, c1 = skeleton_to_csgraph(_testdata.skeleton1)
fig, axes = plt.subplots(1, 2)

draw.overlay_skeleton_networkx(g0, np.transpose(c0), image=_testdata.skeleton0,
                               axis=axes[0])
draw.overlay_skeleton_networkx(g1, np.transpose(c1), image=_testdata.skeleton1,
                               axis=axes[1])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m~/miniconda3/envs/skan_doc/lib/python3.9/site-packages/networkx/drawing/nx_pylab.py:456[0m, in [0;36mdraw_networkx_nodes[0;34m(G, pos, nodelist, node_size, node_color, node_shape, alpha, cmap, vmin, vmax, ax, linewidths, edgecolors, label, margins)[0m
[1;32m    455[0m [38;5;28;01mtry[39;00m:
[0;32m--> 456[0m     xy [38;5;241m=[39m np[38;5;241m.[39masarray([pos[v] [38;5;28;01mfor[39;00m v [38;5;129;01min[39;00m nodelist])
[1;32m    457[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

File [0;32m~/miniconda3/envs/skan_doc/lib/python3.9/site-packages/networkx/drawing/nx_pylab.py:456[0m, in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m    455[0m [38;5;28;01mtry[39;00m:
[0;32m--> 456[0m     xy [38;5;241m=[39m np[38;5;241m.[39masarray([[43mpos[49m[43m[[49m[43mv[49m[43m][49m [38;5;28;01mfor[39;00m v [38;5;129;01min[39;00m nodelist])
[1;32m    457[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

[0;31mKeyError[0m: 2

The above exception was the direct cause of the following exception:

[0;31mNetworkXError[0m                             Traceback (most recent call last)
Input [0;32mIn [9][0m, in [0;36m<cell line: 6>[0;34m()[0m
[1;32m      3[0m g1, c1 [38;5;241m=[39m skeleton_to_csgraph(_testdata[38;5;241m.[39mskeleton1)
[1;32m      4[0m fig, axes [38;5;241m=[39m plt[38;5;241m.[39msubplots([38;5;241m1[39m, [38;5;241m2[39m)
[0;32m----> 6[0m [43mdraw[49m[38;5;241;43m.[39;49m[43moverlay_skeleton_networkx[49m[43m([49m[43mg0[49m[43m,[49m[43m [49m[43mnp[49m[38;5;241;43m.[39;49m[43mtranspose[49m[43m([49m[43mc0[49m[43m)[49m[43m,[49m[43m [49m[43mimage[49m[38;5;241;43m=[39;49m[43m_testdata[49m[38;5;241;43m.[39;49m[43mskeleton0[49m[43m,[49m
[1;32m      7[0m [43m                               [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxes[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m)[49m
[1;32m      8[0m draw[38;5;241m.[39moverlay_skeleton_networkx(g1, np[38;5;241m.[39mtranspose(c1), image[38;5;241m=[39m_testdata[38;5;241m.[39mskeleton1,
[1;32m      9[0m                                axis[38;5;241m=[39maxes[[38;5;241m1[39m])

File [0;32m~/Documents/Dev/skan/src/skan/draw.py:367[0m, in [0;36moverlay_skeleton_networkx[0;34m(csr_graph, coordinates, axis, image, cmap, **kwargs)[0m
[1;32m    365[0m positions [38;5;241m=[39m [38;5;28mdict[39m([38;5;28mzip[39m([38;5;28mrange[39m(coordinates[38;5;241m.[39mshape[[38;5;241m0[39m]), coordinates[:, ::[38;5;241m-[39m[38;5;241m1[39m]))
[1;32m    366[0m _clean_positions_dict(positions, gnx)  [38;5;66;03m# remove nodes not in Graph[39;00m
[0;32m--> 367[0m [43mnx[49m[38;5;241;43m.[39;49m[43mdraw_networkx[49m[43m([49m[43mgnx[49m[43m,[49m[43m [49m[43mpos[49m[38;5;241;43m=[39;49m[43mpositions[49m[43m,[49m[43m [49m[43max[49m[38;5;241;43m=[39;49m[43maxis[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    368[0m [38;5;28;01mreturn[39;00m axis

File [0;32m~/miniconda3/envs/skan_doc/lib/python3.9/site-packages/networkx/drawing/nx_pylab.py:335[0m, in [0;36mdraw_networkx[0;34m(G, pos, arrows, with_labels, **kwds)[0m
[1;32m    332[0m [38;5;28;01mif[39;00m pos [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    333[0m     pos [38;5;241m=[39m nx[38;5;241m.[39mdrawing[38;5;241m.[39mspring_layout(G)  [38;5;66;03m# default to spring layout[39;00m
[0;32m--> 335[0m [43mdraw_networkx_nodes[49m[43m([49m[43mG[49m[43m,[49m[43m [49m[43mpos[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mnode_kwds[49m[43m)[49m
[1;32m    336[0m draw_networkx_edges(G, pos, arrows[38;5;241m=[39marrows, [38;5;241m*[39m[38;5;241m*[39medge_kwds)
[1;32m    337[0m [38;5;28;01mif[39;00m with_labels:

File [0;32m~/miniconda3/envs/skan_doc/lib/python3.9/site-packages/networkx/drawing/nx_pylab.py:458[0m, in [0;36mdraw_networkx_nodes[0;34m(G, pos, nodelist, node_size, node_color, node_shape, alpha, cmap, vmin, vmax, ax, linewidths, edgecolors, label, margins)[0m
[1;32m    456[0m     xy [38;5;241m=[39m np[38;5;241m.[39masarray([pos[v] [38;5;28;01mfor[39;00m v [38;5;129;01min[39;00m nodelist])
[1;32m    457[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:
[0;32m--> 458[0m     [38;5;28;01mraise[39;00m nx[38;5;241m.[39mNetworkXError([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNode [39m[38;5;132;01m{[39;00merr[38;5;132;01m}[39;00m[38;5;124m has no position.[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    460[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(alpha, Iterable):
[1;32m    461[0m     node_color [38;5;241m=[39m apply_alpha(node_color, alpha, nodelist, cmap, vmin, vmax)

[0;31mNetworkXError[0m: Node 2 has no position.
NetworkXError: Node 2 has no position.

